### ISSUE TITLE
Library is instantiating commented out HTML that affects performance

### ISSUE THREAD

**Issue by noahsemus** [henrygd/bigger-picture#13]
I noticed this a while back but for whatever reason it seemed to go away. However, it's now back after updating to the latest version (and also migrating to the latest SvelteKit version, not sure if that could be the problem too) -- that is the fact that for each bigger picture instance a `<!--<Bigger-picture>-->` is inserted into the DOM. This becomes a problem in my case when I have tons of instantiated instances as I'm using the library for every post in a feed. As the new instances are instantiated it breaks a scale transition for the posts within the feed. 

Here's an image of what I mean.

![image](https://user-images.githubusercontent.com/33107099/185473964-437a61e7-4fbd-4f50-aa28-836ce101bcfd.png)

**Comment by henrygd** [comment]
Yeah that's unfortunate. I can look into it more this weekend. Are you using any Svelte devtools extensions by any chance?

I would recommend reducing the number of  bigger picture instances if possible. It looks like they're all added to the body -- have you tried reusing one instance? Unless multiple instances need to be open simultaneously it should be doable.

If it helps, you can also call the `$destroy` method like any other component to scrap an instance and remove it from the DOM.

**Comment by noahsemus** [comment]
I'm not using devtools unfortunately. The way it's built is also not very conducive to multiple instances -- for context it's a reddit site and each image post uses bigger picture as a lightbox. Unless I'm mistaken I'm not sure a singular instance would work in my case.

**Comment by henrygd** [comment]
So it looks like these comments are inserted for every component in dev mode, not just bigger picture. They're removed in the production build, and there may be a way to disable them, but there should also be a way to prevent this many instances in the first place.

On the [demo site](https://biggerpicture.henrygd.me/) I'm using the same instance for five of the seven sections, plus all the code examples. Only the inline gallery and thumbnail example are standalone instances because they need to be mounted in different targets. It looks like your app mounts all the galleries in `document.body`, so unless I'm missing something this should be possible. The gallery content is passed in the open method -- if multiple instances have the same target they're essentially identical. As long as you have one in scope it should be able to be reused.

You can also make a little module that allows you to import a shared instance. Something like the code below should do the job (assuming you're using typescript -- type import works on 1.1.6). Just save that in a ts file and `import { bp } from "..."` in any component.

```js
import { browser } from "$app/env";
import BiggerPicture from "bigger-picture";
import type { BiggerPictureInstance } from "bigger-picture";

let bp: BiggerPictureInstance

if (browser) {
  bp = BiggerPicture({ target: document.body });
}

export { bp };
```

If for some reason this doesn't work and you still have the need to create a new instance every time a gallery is opened, you can destroy everything after it's closed, removing the inserted comment. Something like this:

```js
let bp = BiggerPicture({
  target: document.body,
});

bp.open({
  items,
  onClosed: () => setTimeout(bp.$destroy, 0),
});
```

The `$destroy` method may give you a typescript warning because it's not included in the defined types, but it's a [native Svelte method](https://svelte.dev/docs#run-time-client-side-component-api-$destroy) so should always exist.

If you want, I'd be happy to look at your code and help find a way to make this work better. If you don't want to post it here you can put the relevant parts in a secret gist and email it to me.

**Comment by noahsemus** [comment]
Aha, thanks for the prompt response. I was literally just coming here to say that the commented out elements aren't in production. Luckily, that helps a ton as it doesn't impact the visuals at all. Though, I will take a crack at using a singular instance; the examples you've given should be help enough! Thank you!

**Comment by henrygd** [comment]
No problem. I doubt it affects performance much anyway since nothing is added to the DOM unless a gallery is open.

Easiest way to make the change is probably creating the instance in the parent component and passing to the Bigger-picture components as a prop.

**Comment by noahsemus** [comment]
Closing as issue is solved
