### ISSUE TITLE
Is it possible to do thumbnails without Svelte?

### ISSUE THREAD

**Issue by davidkoh83** [henrygd/bigger-picture#16]
Hi,

Really love what you did here for this lightbox. I was wondering if it is possible to have the lightbox show the thumbnails like in your last demo but only with pure JS without Svelte. Thanks!

**Comment by henrygd** [comment]
It is possible. But just to be clear, the thumbnails are not a part of the library -- just an example of how you can extend it with your own code.

In the future I'm considering a plugin system to make extensions like this efficient and easy to support, but right now I'm sorry to say that if you need thumbnails you'll need to write your own version. Or you could add Svelte to your project and take my example. (You get Svelte for free essentially because bigger-picture uses it internally, see [usage with Svelte](https://github.com/henrygd/bigger-picture#usage-with-svelte).)

I'm going to close the issue since this is about an example and not the library itself, but I'll follow up if you have any other questions.

**Comment by davidkoh83** [comment]
Thanks for your answer =b
