### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')

### ISSUE THREAD

**Issue by razonyang** [henrygd/bigger-picture#26]
Thanks for your awesome package, I got a strange issue when clicking some picture:

```log
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at $ (hb.cbf8fdc36b5a7171bfc892331043f7a4f59f7264bdcd628ad89914aa1e556c98.js:1:21930)
    at Object.m (hb.cbf8fdc36b5a7171bfc892331043f7a4f59f7264bdcd628ad89914aa1e556c98.js:6:9147)
    at Object.p (hb.cbf8fdc36b5a7171bfc892331043f7a4f59f7264bdcd628ad89914aa1e556c98.js:6:12345)
    at Hn (hb.cbf8fdc36b5a7171bfc892331043f7a4f59f7264bdcd628ad89914aa1e556c98.js:4:1104)
    at Pe (hb.cbf8fdc36b5a7171bfc892331043f7a4f59f7264bdcd628ad89914aa1e556c98.js:4:778)
```

Live example: https://hb-theme.hugomods.com/en/blog/2023/03/tutorial/

When clicking the featured image, the `<div class="bp-wrap"></div>` doesn't appear on source code, and produce the error above. But other pages works as expected.

- https://hb-theme.hugomods.com/en/gallery/textures/
- https://hb-theme.hugomods.com/en/blog/2022/02/example-post-with-an-featured-image/

My implementation: https://github.com/hbstack/bigger-picture/blob/main/assets/hb/modules/bigger-picture/js/index.ts

## What I tried?

I've tried to attach the click listener after the `window.load` event instead of `DOMContentLoaded`, and then all pictures work fine.
Am I doing something wrong?

**Comment by henrygd** [comment]
Seems to be a conflict with katex.js. The other pages work because they aren't loading that script, and the problem page works if I block katex.js in the network tab.

It also seems to work if you make sure katex.js is loaded before your main hb.js script by removing the `defer` attribute or moving it above hb.js in html.

I made a stackblitz to test, which I'll link below. You can see that it also works using the `bigger-picture.ts` script which I copied from your example, only changing the bigger-picture import to use `bigger-picture/vanilla`, so the root cause may be something else in your bundle.

https://stackblitz.com/edit/vitejs-vite-fkjanb?file=index.html

**Comment by razonyang** [comment]
Thanks a lot for spending time on this, you're right, there are conflicts somewhere, I'm closing this issue, since it isn't related to this package.

Thanks again for your use tip.

**Comment by henrygd** [comment]
No problem at all
