### ISSUE TITLE
Action?

### ISSUE THREAD

**Issue by howesteve** [henrygd/bigger-picture#28]
Hello,

Can we use this as a svelte action (i.e. use:action)?

Btw you won me at the "Lift Your Skinny Fists Like Antennas to Heaven" in the demo.

Thanks

**Comment by henrygd** [comment]
Not directly but it's easy to make your own depending on what you want to do.

See here for an example: https://stackblitz.com/edit/sveltejs-kit-template-default-s1hf8h?file=src%2Froutes%2F%2Bpage.svelte

Note: I used `bigger-picture/vanilla` because the global / local default transition switch in Svelte 4 broke the opening animation. Probably need to do a 2.0 release at some point to fix it.
