### ISSUE TITLE
activeItem is undefined

### ISSUE THREAD

**Issue by multipliedtwice** [henrygd/bigger-picture#36]
Line 65 throws an error. Maybe because of cloudflare rocket loader, not sure. But sometimes activeItem is undefined
```
8.a0ac303b.js:7 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at r.$$.update (8.a0ac303b.js:7:33773)
    at mt (scheduler.6ba28897.js:1:10177)
    at dt (scheduler.6ba28897.js:1:9910)
r.$$.update @ 8.a0ac303b.js:7
mt @ scheduler.6ba28897.js:1
dt @ scheduler.6ba28897.js:1
Promise.then (async)
_t @ scheduler.6ba28897.js:1
ht @ index.6d6c8704.js:4
(anonymous) @ index.6d6c8704.js:4
H @ 8.a0ac303b.js:7
l @ 8.a0ac303b.js:7
await in l (async)
u @ 8.a0ac303b.js:7
c @ 8.a0ac303b.js:7
c @ rocket-loader.min.js:1
```

**Comment by henrygd** [comment]
When are you seeing this? When you first load the page? When you try to open a gallery?

It's going to be very difficult to troubleshoot without a reproduction.

**Comment by multipliedtwice** [comment]
Hello, when opening a gallery. It happens randomly, sometimes even on consequent open.

It's some edge case because I also can't reproduce it locally. It appears only in prod. 

Could you hardcode undefined as an input value and suppress the error?

**Comment by henrygd** [comment]
Have you tried disabling rocket loader? Or [excluding your bigger-picture / bundle script](https://developers.cloudflare.com/speed/optimization/content/rocket-loader/ignore-javascripts/#:~:text=If%20the%20script%20you%20want,added%20before%20the%20src%20attribute.)? 

We can't have `activeItem` fall back to undefined because it's relied upon in many other parts of the library. As long as the items are valid it should fall back to being the first item.

If it's only happening in production there must be something unique to the production environment that's breaking it.

**Comment by henrygd** [comment]
Sorry this closed automatically because of commits that referenced it. I don't think the issue is caused by the library but if you still want help figuring it out, let me know.
