### ISSUE TITLE
chrome warns of non-passive event listeners

### ISSUE THREAD

**Issue by ellemenno** [henrygd/bigger-picture#40]
when navigating through a gallery, each image load prompts the following log message in Chrome:
```
demo.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

this can be seen by opening the javascript console on the [demo page](https://biggerpicture.henrygd.me/), and setting the log filter to include 'Verbose'.

**Comment by henrygd** [comment]
This is intentional to stop background scrolling when zooming in / out. The listener is removed when the gallery is closed so there shouldn't be any actual impact to scroll performance.

If someone knows a better way to do this, let me know. But I experimented back when I first made the library and this seemed like the best approach at the time.
