### ISSUE TITLE
Could not find a declaration file for module 'bigger-picture/svelte'

### ISSUE THREAD

**Issue by bugproof** [henrygd/bigger-picture#48]
![image](https://github.com/user-attachments/assets/8ce66195-6fc3-4e82-bd5c-aa23112168f1)

![image](https://github.com/user-attachments/assets/3da76a90-eb57-42af-8cb1-1d6c8373d688)

This import doesn't work somehow... When I import just 'bigger-picture' it works fine.

**Comment by henrygd** [comment]
Looks like it's because `.svelte-kit/tsconfig.json` changed `compilerOptions.moduleResolution` from `node` (which I think is the default and what older SvelteKit versions used) to `bundler`.

You can fix it for now by adding `"moduleResolution": "node"` to `compilerOptions` in `tsconfig.json`. Doesn't seem to break anything.

I'll add a fix for it when I have a couple hours free time to read about obscure typescript / package.json rules and conflicts :grinning:
