### ISSUE TITLE
Ability to open inline galleries in fullscreen

### ISSUE THREAD

**Issue by noahsemus** [henrygd/bigger-picture#8]
Could be missing something, but is there the ability to open inline gallery images in fullscreen rather than have the controls fade away on click? 

I've tried a sort of weird workaround where I try to open a second BiggerPicture instance, but it doesn't seem to work as the original inline instance instantiates its own items.

**Comment by henrygd** [comment]
Yeah by default it only zooms within the container. If the controls are fading on click you're probably on a mobile device, so you need to double tap or pinch.

I agree that inline galleries are not a good experience on small screens and it would be nice to be able to expand outside the bounds of the container.

A second instance opening full screen is a good idea and may be simple enough to add as an optional behavior (or default to it under a certain width). At the very least I can make some tweaks so that it's easier to accomplish on your own.

May not have the opportunity until around midweek but will definitely look into it.

**Comment by henrygd** [comment]
Added the [`onImageClick`](https://github.com/henrygd/bigger-picture/blob/main/readme.md#onimageclick) method to make this easier. Here's an example:

https://codesandbox.io/s/bp-inline-second-instance-gqzkcw

Let me know if this works for you.

**Comment by noahsemus** [comment]
This is great! Works on my end too. 

One small question I have is if there a way to keep the gallery while in fullscreen? IE being able to swipe between images in the lightbox state. I tried setting the same key for `items` as the parent instance, but obviously that then breaks the shared element animation. 

I attempted to iterate across my original array with a `.map()`, add in the `element` to be `bpImg`, and then I wrapped that in `.flat()`, but for some reason that still broke the transition.

**Comment by henrygd** [comment]
I'll check everything in browserstack on Tuesday. I'm on a bad cell hotspot right now and it won't cooperate. I did manage to make some multi-image examples, though.

This one doesn't update the inline gallery -- just fades back to the image it was on when opened. (I'll give `onClose` its own container  / activeItem params in the next release).

https://codesandbox.io/s/bp-inline-second-instance-forked-gsgu3t

This one updates the inline gallery in the background, but it's a bit convoluted because the looping needs to be handled manually.

https://codesandbox.io/s/bp-inline-second-instance-forked-65hylq

This one updates the inline gallery, but blacks it out so you can just use `setPosition`.

https://codesandbox.io/s/bp-inline-second-instance-forked-ezfzfv

**Comment by henrygd** [comment]
Cool, no problem. I'll sort out the mobile click issue and try to have a release out this week.

Let me know if you run into any other issues.
